package com.taskmanagement.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserDTO {
    private Long id;
    private String username;
    private String email;
    private String fullName;
    private String role;
    
    // No need for manual constructor - Lombok's @AllArgsConstructor generates it
    
    // Getters and setters are generated by @Data, so you can remove these too
    // But if you want to keep them for clarity, that's fine - @Data will override them
}